### PR TITLE
Feature/edit task

### PR DESCRIPTION
**Pull request by sammiepls**
Okay, how's this? Currently all logic in the list though, would want to refactor it into another list item component if this logic is okay with you 🙌

### CODE REVIEW

**Comment by talentedunicorn** [comment]
It look good...almost there:

- Don't allow saving of empty edits (should probably use the same logic as add 🤔)
- Let's do some tests 😄 

Have you used [React Context](https://reactjs.org/docs/context.html) before? I'm thinking of moving the logic there so we avoid passing functionality into props

**Comment by sammiepls** [comment]
Have not used the Context, but have touched a bit on Redux only.

**Comment by talentedunicorn** [comment]
> Have not used the Context, but have touched a bit on Redux only.

Oh OK, well Redux underlying uses context API but react exposes this so you can easily use it now. [Here's an article](https://alligator.io/react/context-api/) explaining that a bit more. 
Also have a look at the implementation on [this branch](https://github.com/talentedunicorn/todolist/tree/use-context) where I've moved the logic to context. Let me know if you have questions :)

**Comment by talentedunicorn** [comment]
Hey i've added some testing and edit mode on the PR #10 
Check it out, let me know if you have questions/comments about context etc..
Thanks for contributing and please don't stop 🙌 😄 
Will close this for now

**Pull request closed without merging**
